# Generated by Django 3.2.12 on 2023-10-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='readingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
