# Generated by Django 3.2.12 on 2023-11-02 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20231029_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmemo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
