# Generated by Django 3.2.12 on 2023-09-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_readingmemo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='started_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
