# Generated by Django 3.2.12 on 2023-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_readingrecord_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
