# Generated by Django 3.2.12 on 2023-10-24 01:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_delete_bookselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0005_alter_readingrecord_started_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingrecord',
            unique_together={('user', 'book')},
        ),
    ]
