# Generated by Django 3.2.12 on 2023-10-27 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN意外のキー')),
                ('title', models.CharField(max_length=255, verbose_name='書籍名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='書籍説明')),
                ('thumbnail', models.URLField(blank=True, null=True, verbose_name='サムネイル')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='出版日')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社')),
                ('views', models.IntegerField(default=0, verbose_name='閲覧数')),
                ('is_clean', models.BooleanField(default=False, verbose_name='整備されたデータ判定')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='表示名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookshelfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookshelf')),
            ],
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='books',
            field=models.ManyToManyField(through='book.BookshelfBook', to='book.Book'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genre')),
            ],
            options={
                'unique_together': {('book', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='book.BookAuthor', to='book.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bookcategory', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(through='book.BookGenre', to='book.Genre'),
        ),
    ]
