# Generated by Django 3.2.12 on 2023-10-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN意外のキー'),
        ),
    ]
