# Generated by Django 3.2.12 on 2023-10-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20231030_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
        migrations.AddField(
            model_name='book',
            name='is_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='論理削除'),
        ),
    ]
