# Generated by Django 3.2.12 on 2023-09-28 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
