# Generated by Django 3.2.12 on 2023-10-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20231030_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_delete',
            new_name='delete_time',
        ),
    ]
