# Generated by Django 3.2.12 on 2023-10-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_is_delete_book_delete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='delete_time',
        ),
    ]
