# Generated by Django 3.2.12 on 2023-10-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_book_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Amazonの購入URL'),
        ),
    ]
