# Generated by Django 3.2.12 on 2023-09-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20231001_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='books',
        ),
        migrations.CreateModel(
            name='BookshelfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookshelf')),
            ],
        ),
    ]
