# Generated by Django 3.2.12 on 2023-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20231001_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='books',
            field=models.ManyToManyField(through='book.BookshelfBook', to='book.Book'),
        ),
    ]
