# Generated by Django 3.2.12 on 2023-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_amazon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_sensitive',
            field=models.BooleanField(default=False, verbose_name='センシティブな内容'),
        ),
    ]
