# Generated by Django 3.2.12 on 2023-11-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_is_sensitive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookshelfbook',
            unique_together={('bookshelf', 'book')},
        ),
    ]
