# Generated by Django 3.2.12 on 2023-11-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookshelfbook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ISBN意外のキー'),
        ),
    ]
