# Generated by Django 3.2.12 on 2023-10-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_bookselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookselection',
            name='title',
            field=models.CharField(default='セレクション名', max_length=126, verbose_name='セレクション名'),
        ),
    ]
