# Generated by Django 3.2.12 on 2023-10-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_bookselection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookselection',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='in_selections', to='book.Book'),
        ),
    ]
