# Generated by Django 3.2.12 on 2023-10-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_bookselection_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSelection',
        ),
    ]
