# Generated by Django 3.2.12 on 2023-09-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
