# Generated by Django 3.2.12 on 2023-10-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('error', 'エラー・バグ報告'), ('book', '書籍問い合わせ'), ('other', 'その他')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_responded', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考欄')),
            ],
        ),
    ]
