# Generated by Django 3.2.12 on 2023-10-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='備考欄'),
        ),
    ]
