# Generated by Django 3.2.12 on 2023-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('error', 'エラー・バグ報告'), ('book', '書籍問い合わせ'), ('other', 'その他')], max_length=10),
        ),
    ]
