# Generated by Django 3.2.12 on 2023-10-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_selections',
            field=models.IntegerField(default=3, verbose_name='セレクション作成の有効数。'),
        ),
    ]
