# Generated by Django 3.2.12 on 2023-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_available_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
