# Generated by Django 3.2.12 on 2023-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_is_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_ai',
            field=models.IntegerField(default=3, verbose_name='AIの利用可能数。'),
        ),
    ]
