# Generated by Django 3.2.12 on 2023-09-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookshelf_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0, verbose_name='閲覧数'),
        ),
    ]
