# Generated by Django 3.2.12 on 2023-11-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
