# Generated by Django 3.2.12 on 2023-11-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
