# Generated by Django 3.2.12 on 2023-09-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_readingmemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmemo',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
