# Generated by Django 3.2.12 on 2023-10-27 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='セレクション名', max_length=126, verbose_name='セレクション名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='セレクション説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionBookRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.bookselection')),
            ],
            options={
                'unique_together': {('selection', 'book')},
            },
        ),
        migrations.AddField(
            model_name='bookselection',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='in_selections', through='selection.SelectionBookRelation', to='book.Book'),
        ),
        migrations.AddField(
            model_name='bookselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookSelectionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='selection.bookselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'selection')},
            },
        ),
        migrations.CreateModel(
            name='BookSelectionFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='selection.bookselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'selection')},
            },
        ),
    ]
