# Generated by Django 3.2.12 on 2023-10-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionbookrelation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
