# Generated by Django 3.2.12 on 2023-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_bookselection_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookselection',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
