# Generated by Django 3.2.12 on 2023-10-24 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selection', '0002_alter_selectionbookrelation_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSelectionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='selection.bookselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'selection')},
            },
        ),
    ]
