# Generated by Django 3.2.12 on 2023-10-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_bookselectionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookselection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
