name: デプロイ(mainブランチ)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lightsailにデプロイ(main)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USER }}
        port: ${{ secrets.MAIN_PORT }}
        key: ${{ secrets.MAIN_KEY }}
        script: |
          cd ${{ secrets.MAIN_DIR }}
          echo "git pull開始"
          git pull
          docker-compose restart
          docker-compose exec web python manage.py collectstatic --noinput
          docker-compose exec web python manage.py migrate
          echo "デプロイ完了"
